/*
 * TFT_eSPI_LCC_Setup.h
 *
 * Bridge file picked up by TFT_eSPI_RA8876's User_Setup_Select.h when the
 * library source files are compiled.  Arduino IDE adds the sketch directory to
 * the library include path, so this file is found automatically — no library
 * edits are ever needed when switching boards.
 *
 * DO NOT EDIT THIS FILE.  Change ProjectConfig.h instead.
 *
 * How it works:
 *   1. ProjectConfig.h defines the active board (LCC_BOARD_STEPPER_V24 etc.)
 *   2. This file maps that choice to the correct TFT_eSPI display-config header.
 *   3. User_Setup_Select.h (library) includes this file, so the library binary
 *      is always compiled with the same display settings as the sketch.
 */

#include "ProjectConfig.h"

#if defined(LCC_BOARD_STEPPER_V24)
  #include "display_configs/DisplayConfig_SSD1963_parallel.h"   // SSD1963 8-bit parallel, 800x480
#elif defined(LCC_BOARD_STEPPER_V27)
  #include "display_configs/DisplayConfig_RA8876_SPI.h"         // RA8876 SPI, 1024x600
#else
  #error "TFT_eSPI_LCC_Setup.h: no board defined in ProjectConfig.h"
#endif
