/** \copyright
* Copyright (c) 2024, Jim Kueneman
* All rights reserved.
*
* Redistribution and use in source and binary forms, with or without
* modification, are permitted provided that the following conditions are met:
*
*  - Redistributions of source code must retain the above copyright notice,
*    this list of conditions and the following disclaimer.
*
*  - Redistributions in binary form must reproduce the above copyright notice,
*    this list of conditions and the following disclaimer in the documentation
*    and/or other materials provided with the distribution.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
* AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
* IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
* ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
* LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
* CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
* SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
* INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
* CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
* ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
* POSSIBILITY OF SUCH DAMAGE.
*
* @file openlcb_node.c
* @brief Implementation of OpenLCB node allocation, enumeration, and lifecycle management
* @author Jim Kueneman
* @date 17 Jan 2026
*/

#include "openlcb_node.h"

#include <assert.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h> // printf

#include "openlcb_types.h"
#include "openlcb_defines.h"
#include "openlcb_utilities.h"
#include "openlcb_buffer_store.h"

    /**
    * @brief Bit shift offset for generating event IDs from node IDs
    *
    * @details Event IDs are generated by shifting the 48-bit node ID left by 16 bits,
    * creating a 64-bit event ID space. The lower 16 bits are used for individual
    * event numbering within the node's allocated space.
    *
    * @see _generate_event_ids - Uses this constant for event ID generation
    */
#define OPENLCB_EVENT_ID_OFFSET 16

static openlcb_nodes_t _openlcb_nodes;
static uint8_t _node_enum_index_array[MAX_NODE_ENUM_KEY_VALUES];

static const interface_openlcb_node_t *_interface;

    /**
    * @brief Clears and initializes a single node structure
    *
    * @details Algorithm:
    * -# Clear all node state fields to zero
    * -# Set run_state to RUNSTATE_INIT
    * -# Clear all node flags (allocated, initialized, permitted, etc.)
    * -# Reset timer tick counter
    * -# Clear owner_node and index fields
    * -# Set last_received_datagram pointer to NULL
    * -# Clear all consumer event IDs and set status to EVENT_STATUS_UNKNOWN
    * -# Clear all producer event IDs and set status to EVENT_STATUS_UNKNOWN
    * -# Stop any running consumer/producer enumerations
    *
    * Internal use only - called during initialization and allocation.
    *
    * @verbatim
    * @param openlcb_node Pointer to node structure to clear
    * @endverbatim
    *
    * @warning Pointer must NOT be NULL - no NULL check performed
    * @warning Does not clear enumeration index array - that is global state
    *
    * @see OpenLcbNode_initialize - Calls this for all nodes during startup
    * @see OpenLcbNode_allocate - Calls this before initializing new node
    */
static void _clear_node(openlcb_node_t *openlcb_node)
{

    openlcb_node->alias = 0;
    openlcb_node->id = 0;
    openlcb_node->seed = 0;
    openlcb_node->state.run_state = RUNSTATE_INIT;
    openlcb_node->state.allocated = false;
    openlcb_node->state.duplicate_id_detected = false;
    openlcb_node->state.initialized = false;
    openlcb_node->state.permitted = false;
    openlcb_node->state.openlcb_datagram_ack_sent = false;
    openlcb_node->state.resend_datagram = false;
    openlcb_node->state.firmware_upgrade_active = false;
    openlcb_node->timerticks = 0;
    openlcb_node->owner_node = 0;
    openlcb_node->index = 0;

    openlcb_node->last_received_datagram = NULL;

    openlcb_node->consumers.count = 0;
    for (int i = 0; i < USER_DEFINED_CONSUMER_COUNT; i++) {

        openlcb_node->consumers.list[i].event = 0;
        openlcb_node->consumers.list[i].status = EVENT_STATUS_UNKNOWN;

    }

    openlcb_node->producers.count = 0;
    for (int j = 0; j < USER_DEFINED_PRODUCER_COUNT; j++) {

        openlcb_node->producers.list[j].event = 0;
        openlcb_node->producers.list[j].status = EVENT_STATUS_UNKNOWN;

    }

    openlcb_node->consumers.range_count = 0;
    for (int i = 0; i < USER_DEFINED_CONSUMER_RANGE_COUNT; i++)
    {

        openlcb_node->consumers.range_list[i].start_base = NULL_EVENT_ID;
        openlcb_node->consumers.range_list[i].event_count = 0;
    }

    openlcb_node->producers.range_count = 0;
    for (int j = 0; j < USER_DEFINED_PRODUCER_RANGE_COUNT; j++)
    {

        openlcb_node->producers.range_list[j].start_base = NULL_EVENT_ID;
        openlcb_node->producers.range_list[j].event_count = 0;
    }

    openlcb_node->producers.enumerator.running = false;
    openlcb_node->consumers.enumerator.running = false;


}

    /**
    * @brief Initializes the OpenLCB Node management module
    *
    * @details Algorithm:
    * -# Store interface pointer (may be NULL if no callbacks needed)
    * -# Clear all node structures in the pool by calling _clear_node()
    * -# Reset node count to zero
    * -# Initialize enumeration index array to zero for all keys
    *
    * Use cases:
    * - Called once during application initialization
    * - Required before OpenLcbNode_allocate() can be used
    *
    * @verbatim
    * @param interface Pointer to interface structure containing optional callbacks,
    *                  or NULL if no callbacks needed
    * @endverbatim
    *
    * @warning MUST be called exactly once during initialization
    * @warning NOT thread-safe
    *
    * @attention Call before any other OpenLcbNode functions
    *
    * @see OpenLcbNode_allocate - Allocates nodes after initialization
    * @see interface_openlcb_node_t - Structure definition for callbacks
    * @see _clear_node - Internal function used to clear each node
    */
void OpenLcbNode_initialize(const interface_openlcb_node_t *interface)
{

    _interface = interface;

    for (int i = 0; i < USER_DEFINED_NODE_BUFFER_DEPTH; i++) {

        _clear_node(&_openlcb_nodes.node[i]);

    }

    _openlcb_nodes.count = 0;

    for (int j = 0; j < MAX_NODE_ENUM_KEY_VALUES; j++) {

        _node_enum_index_array[j] = 0;

    }

}

    /**
    * @brief Gets the first node in the pool for enumeration
    *
    * @details Algorithm:
    * -# Validate that key is within valid range (0 to MAX_NODE_ENUM_KEY_VALUES-1)
    * -# If key invalid, return NULL
    * -# Reset enumeration index for this key to 0
    * -# Check if any nodes are allocated (count > 0)
    * -# If no nodes, return NULL
    * -# Return pointer to first node in pool
    *
    * Use cases:
    * - Beginning iteration through all allocated nodes
    * - Main state machine enumeration (typically key=0)
    * - Login state machine enumeration (typically key=1)
    *
    * @verbatim
    * @param key Enumeration key identifying which enumerator is requesting (0 to MAX_NODE_ENUM_KEY_VALUES-1)
    * @endverbatim
    *
    * @return Pointer to the first allocated node, or NULL if no nodes exist or key invalid
    *
    * @warning Returns NULL if key >= MAX_NODE_ENUM_KEY_VALUES
    *
    * @attention Use unique key values for independent simultaneous enumerations
    * @attention Must use same key value for get_first and subsequent get_next calls
    *
    * @see OpenLcbNode_get_next - Gets subsequent nodes in enumeration
    * @see MAX_NODE_ENUM_KEY_VALUES - Maximum number of simultaneous enumerators
    */
openlcb_node_t *OpenLcbNode_get_first(uint8_t key)
{

    if (key >= MAX_NODE_ENUM_KEY_VALUES) {

        return NULL;

    }

    _node_enum_index_array[key] = 0;

    if (_openlcb_nodes.count == 0) {

        return NULL;

    }

    return &_openlcb_nodes.node[_node_enum_index_array[key]];
}

    /**
    * @brief Gets the next node in the enumeration sequence
    *
    * @details Algorithm:
    * -# Validate that key is within valid range (0 to MAX_NODE_ENUM_KEY_VALUES-1)
    * -# If key invalid, return NULL
    * -# Increment enumeration index for this key by 1
    * -# Check if index has reached or exceeded node count
    * -# If at end of list, return NULL
    * -# Return pointer to node at current index position
    *
    * Use cases:
    * - Continuing iteration through allocated nodes
    * - Processing all nodes in the pool
    *
    * @verbatim
    * @param key Enumeration key identifying which enumerator is requesting (same as get_first)
    * @endverbatim
    *
    * @return Pointer to the next allocated node, or NULL if at end of list or key invalid
    *
    * @warning Returns NULL if key >= MAX_NODE_ENUM_KEY_VALUES
    *
    * @attention Use same key value as the corresponding get_first call
    *
    * @see OpenLcbNode_get_first - Initializes enumeration
    */
openlcb_node_t *OpenLcbNode_get_next(uint8_t key)
{

    if (key >= MAX_NODE_ENUM_KEY_VALUES) {

        return NULL;

    }

    _node_enum_index_array[key]++;

    if (_node_enum_index_array[key] >= _openlcb_nodes.count) {

        return NULL;

    }

    return &_openlcb_nodes.node[_node_enum_index_array[key]];
}

    /**
    * @brief Generates auto-created event IDs for a node's producers and consumers
    *
    * @details Algorithm:
    * -# Calculate base event ID by shifting node ID left by OPENLCB_EVENT_ID_OFFSET bits
    * -# Initialize indexer to 0
    * -# For each consumer to auto-create (0 to consumer_count_autocreate):
    *    - If within array bounds (< USER_DEFINED_CONSUMER_COUNT):
    *      - Set consumer event ID to base + indexer
    *      - Increment consumer count
    *      - Increment indexer
    * -# Reset indexer to 0 for producers
    * -# For each producer to auto-create (0 to producer_count_autocreate):
    *    - If within array bounds (< USER_DEFINED_PRODUCER_COUNT):
    *      - Set producer event ID to base + indexer
    *      - Increment producer count
    *      - Increment indexer
    * -# Clear consumer and producer enumeration states
    *
    * Event ID Generation Example:
    * - node_id = 0x050101010155
    * - base = 0x0501010101550000 (node_id << 16)
    * - Consumer[0] = 0x0501010101550000
    * - Consumer[1] = 0x0501010101550001
    * - Producer[0] = 0x0501010101550000 (same as Consumer[0])
    * - Producer[1] = 0x0501010101550001
    *
    * Internal use only - called during node allocation.
    *
    * @verbatim
    * @param openlcb_node Pointer to node structure to generate event IDs for
    * @endverbatim
    *
    * @warning Pointer must NOT be NULL - no NULL check performed
    * @warning Silently limits creation to array bounds to prevent buffer overrun
    *
    * @note Consumers and producers share the same event ID space starting from base
    *
    * @see OpenLcbNode_allocate - Calls this during node allocation
    * @see OPENLCB_EVENT_ID_OFFSET - Bit shift constant used for base calculation
    */
static void _generate_event_ids(openlcb_node_t *openlcb_node)
{

    uint64_t node_id = openlcb_node->id << OPENLCB_EVENT_ID_OFFSET;
    uint16_t indexer = 0;

    openlcb_node->consumers.count = 0;
    for (int i = 0; i < openlcb_node->parameters->consumer_count_autocreate; i++) {

        if (i < USER_DEFINED_CONSUMER_COUNT) { // safety net

            openlcb_node->consumers.list[i].event = node_id + indexer;
            openlcb_node->consumers.count++;
            indexer++;

        }

    }

    indexer = 0;
    openlcb_node->producers.count = 0;
    for (int j = 0; j < openlcb_node->parameters->producer_count_autocreate; j++) {

        if (j < USER_DEFINED_PRODUCER_COUNT) { // safety net

            openlcb_node->producers.list[j].event = node_id + indexer;
            openlcb_node->producers.count++;
            indexer++;

        }

    }

    openlcb_node->consumers.enumerator.running = false;
    openlcb_node->consumers.enumerator.enum_index = 0;

    openlcb_node->producers.enumerator.running = false;
    openlcb_node->producers.enumerator.enum_index = 0;

}

    /**
    * @brief Allocates a new OpenLCB node with specified configuration
    *
    * @details Algorithm:
    * -# Search through node pool for first unallocated slot
    * -# When unallocated slot found:
    *    - Clear node structure via _clear_node()
    *    - Store node_parameters pointer (not copied)
    *    - Store node_id
    *    - Store array index in node structure
    *    - Generate auto-created event IDs via _generate_event_ids()
    *    - Increment global node count
    *    - Mark node as allocated (last step for thread safety)
    *    - Return pointer to allocated node
    * -# If no free slots found, return NULL
    *
    * Use cases:
    * - Creating virtual nodes for the application
    * - Setting up nodes with specific event producer/consumer configurations
    *
    * @verbatim
    * @param node_id 64-bit unique OpenLCB node identifier for this node
    * @param node_parameters Pointer to configuration structure defining node capabilities
    *                        (producer count, consumer count, etc.)
    * @endverbatim
    *
    * @return Pointer to allocated and initialized node structure, or NULL if pool is full
    *
    * @warning Returns NULL when node pool exhausted - caller MUST check for NULL
    * @warning Pointer to node_parameters is stored, not copied - must remain valid
    * @warning NOT thread-safe
    *
    * @attention Always check return value for NULL before use
    * @attention Each node must have a unique node_id
    *
    * @see OpenLcbNode_initialize - Must be called first
    * @see OpenLcbNode_find_by_node_id - Finds previously allocated nodes
    * @see node_parameters_t - Configuration structure definition
    * @see _clear_node - Internal function to clear node structure
    * @see _generate_event_ids - Internal function to generate event IDs
    */
openlcb_node_t *OpenLcbNode_allocate(uint64_t node_id, const node_parameters_t *node_parameters)
{

    for (int i = 0; i < USER_DEFINED_NODE_BUFFER_DEPTH; i++) {

        if (!_openlcb_nodes.node[i].state.allocated) {

            _clear_node(&_openlcb_nodes.node[i]);

            _openlcb_nodes.node[i].parameters = node_parameters;
            _openlcb_nodes.node[i].id = node_id;
            _openlcb_nodes.node[i].index = (uint8_t)i;

            _generate_event_ids(&_openlcb_nodes.node[i]);

            _openlcb_nodes.count++;

            // last step is to mark it allocated
            _openlcb_nodes.node[i].state.allocated = true;

            return &_openlcb_nodes.node[i];
        }

    }

    return NULL;
}

    /**
    * @brief Finds a node by its CAN alias
    *
    * @details Algorithm:
    * -# Iterate through all allocated nodes (0 to count-1)
    * -# For each node:
    *    - Compare node alias with search alias
    *    - If match found, return pointer to node
    * -# If no match found after checking all nodes, return NULL
    *
    * Use cases:
    * - Resolving incoming CAN messages to their source node
    * - Mapping CAN alias to full node structure
    *
    * @verbatim
    * @param alias 12-bit CAN alias to search for
    * @endverbatim
    *
    * @return Pointer to node with matching alias, or NULL if not found
    *
    * @note Linear search through all allocated nodes
    *
    * @see OpenLcbNode_find_by_node_id - Finds node by 64-bit ID instead
    * @see openlcb_node_t - Node structure containing alias field
    */
openlcb_node_t *OpenLcbNode_find_by_alias(uint16_t alias)
{

    for (int i = 0; i < _openlcb_nodes.count; i++) {

        if (_openlcb_nodes.node[i].alias == alias) {

            return &_openlcb_nodes.node[i];

        }

    }

    return NULL;
}

    /**
    * @brief Finds a node by its 64-bit OpenLCB node ID
    *
    * @details Algorithm:
    * -# Iterate through all allocated nodes (0 to count-1)
    * -# For each node:
    *    - Compare node ID with search node_id
    *    - If match found, return pointer to node
    * -# If no match found after checking all nodes, return NULL
    *
    * Use cases:
    * - Resolving full OpenLCB messages to their source node
    * - Looking up node by globally unique identifier
    *
    * @verbatim
    * @param node_id 64-bit OpenLCB node identifier to search for
    * @endverbatim
    *
    * @return Pointer to node with matching node ID, or NULL if not found
    *
    * @note Linear search through all allocated nodes
    *
    * @see OpenLcbNode_find_by_alias - Finds node by CAN alias instead
    * @see OpenLcbNode_allocate - Creates nodes with specified node_id
    */
openlcb_node_t *OpenLcbNode_find_by_node_id(uint64_t node_id)
{

    for (int i = 0; i < _openlcb_nodes.count; i++) {

        if (_openlcb_nodes.node[i].id == node_id) {

            return &_openlcb_nodes.node[i];

        }

    }

    return NULL;
}

    /**
    * @brief 100ms timer tick handler for all nodes
    *
    * @details Algorithm:
    * -# Iterate through all allocated nodes (0 to count-1)
    * -# For each node:
    *    - Increment timerticks counter by 1
    * -# If interface callback is registered:
    *    - Call interface->on_100ms_timer_tick()
    *
    * Use cases:
    * - Called by system timer every 100ms
    * - Provides timing for protocol state machines
    *
    * @warning NOT thread-safe
    *
    * @attention Must be called every 100ms for proper protocol timing
    *
    * @see interface_openlcb_node_t - Contains optional callback
    * @see openlcb_node_t - Node structure containing timerticks field
    */
void OpenLcbNode_100ms_timer_tick(void)
{

    for (int i = 0; i < _openlcb_nodes.count; i++) {

        _openlcb_nodes.node[i].timerticks++;

    }

    if (_interface && _interface->on_100ms_timer_tick) {

        _interface->on_100ms_timer_tick();

    }

}

    /**
    * @brief Resets all nodes to initial uninitialized state
    *
    * @details Algorithm:
    * -# Iterate through all allocated nodes (0 to count-1)
    * -# For each node:
    *    - Set run_state to RUNSTATE_INIT
    *    - Clear permitted flag
    *    - Clear initialized flag
    *
    * Does not deallocate nodes or clear configuration data. Used when restarting
    * the network login sequence after error or disconnect.
    *
    * Use cases:
    * - Restarting network login after error
    * - Resetting all nodes to power-up state
    * - Recovering from network disconnect
    *
    * @warning Does not deallocate nodes or free memory
    * @warning NOT thread-safe
    *
    * @see RUNSTATE_INIT - Initial run state value
    * @see openlcb_node_t - Node structure containing state fields
    */
void OpenLcbNode_reset_state(void)
{

    for (int i = 0; i < _openlcb_nodes.count; i++) {

        _openlcb_nodes.node[i].state.run_state = RUNSTATE_INIT;
        _openlcb_nodes.node[i].state.permitted = false;
        _openlcb_nodes.node[i].state.initialized = false;

    }

}
