/*
 * Auto-generated Configuration Memory Map
 * Generated: 2026-02-23T15:46:37.009Z
 * Source: CDI XML Document
 */

#ifndef CONFIG_MEM_MAP_H
#define CONFIG_MEM_MAP_H

#include <stdint.h>

/* Segment 0 */

/* Node -> Node ID -> Node Name */
#define NODE_NODE_ID_NODE_NAME_ADDR 0x0000
#define NODE_NODE_ID_NODE_NAME_SIZE 62

/* Node -> Node ID -> Node Description */
#define NODE_NODE_ID_NODE_DESCRIPTION_ADDR 0x003E
#define NODE_NODE_ID_NODE_DESCRIPTION_SIZE 63

/* Segment 1 */

/* Reset Control -> Flag */
#define RESET_CONTROL_FLAG_ADDR 0x007D
#define RESET_CONTROL_FLAG_SIZE 1

/* Segment 2 */

/* Parameters -> Track -> Track Count */
#define PARAMETERS_TRACK_TRACK_COUNT_ADDR 0x007E
#define PARAMETERS_TRACK_TRACK_COUNT_SIZE 1

/* Parameters -> Track -> Home Track */
#define PARAMETERS_TRACK_HOME_TRACK_ADDR 0x007F
#define PARAMETERS_TRACK_HOME_TRACK_SIZE 1

/* Parameters -> Track -> Enable Reference Correction */
#define PARAMETERS_TRACK_ENABLE_REFERENCE_CORRECTION_ADDR 0x0080
#define PARAMETERS_TRACK_ENABLE_REFERENCE_CORRECTION_SIZE 1

/* Parameters -> Track -> Rehome */
#define PARAMETERS_TRACK_REHOME_ADDR 0x0081
#define PARAMETERS_TRACK_REHOME_SIZE 8

/* Parameters -> Track -> Increment Track */
#define PARAMETERS_TRACK_INCREMENT_TRACK_ADDR 0x0089
#define PARAMETERS_TRACK_INCREMENT_TRACK_SIZE 8

/* Parameters -> Track -> Decrement Track */
#define PARAMETERS_TRACK_DECREMENT_TRACK_ADDR 0x0091
#define PARAMETERS_TRACK_DECREMENT_TRACK_SIZE 8

/* Parameters -> Track -> Rotate Track 180 degrees */
#define PARAMETERS_TRACK_ROTATE_TRACK_180_DEGREES_ADDR 0x0099
#define PARAMETERS_TRACK_ROTATE_TRACK_180_DEGREES_SIZE 8

/* Parameters -> Track -> Toggle Bridge Lights */
#define PARAMETERS_TRACK_TOGGLE_BRIDGE_LIGHTS_ADDR 0x00A1
#define PARAMETERS_TRACK_TOGGLE_BRIDGE_LIGHTS_SIZE 8

/* Parameters -> Track -> Tracks -> REP_0 -> Description */
#define PARAMETERS_TRACK_TRACKS_REP_0_DESCRIPTION_ADDR 0x00A9
#define PARAMETERS_TRACK_TRACKS_REP_0_DESCRIPTION_SIZE 25

/* Parameters -> Track -> Tracks -> REP_0 -> Short Name */
#define PARAMETERS_TRACK_TRACKS_REP_0_SHORT_NAME_ADDR 0x00C2
#define PARAMETERS_TRACK_TRACKS_REP_0_SHORT_NAME_SIZE 5

/* Parameters -> Track -> Tracks -> REP_0 -> Align Front */
#define PARAMETERS_TRACK_TRACKS_REP_0_ALIGN_FRONT_ADDR 0x00C7
#define PARAMETERS_TRACK_TRACKS_REP_0_ALIGN_FRONT_SIZE 8

/* Parameters -> Track -> Tracks -> REP_0 -> Align Back */
#define PARAMETERS_TRACK_TRACKS_REP_0_ALIGN_BACK_ADDR 0x00CF
#define PARAMETERS_TRACK_TRACKS_REP_0_ALIGN_BACK_SIZE 8

/* Parameters -> Track -> Tracks -> REP_0 -> Stepper Position in Steps */
#define PARAMETERS_TRACK_TRACKS_REP_0_STEPPER_POSITION_IN_STEPS_ADDR 0x00D7
#define PARAMETERS_TRACK_TRACKS_REP_0_STEPPER_POSITION_IN_STEPS_SIZE 4

/* Parameters -> Track -> Tracks -> REP_1 -> Description */
#define PARAMETERS_TRACK_TRACKS_REP_1_DESCRIPTION_ADDR 0x00DB
#define PARAMETERS_TRACK_TRACKS_REP_1_DESCRIPTION_SIZE 25

/* Parameters -> Track -> Tracks -> REP_1 -> Short Name */
#define PARAMETERS_TRACK_TRACKS_REP_1_SHORT_NAME_ADDR 0x00F4
#define PARAMETERS_TRACK_TRACKS_REP_1_SHORT_NAME_SIZE 5

/* Parameters -> Track -> Tracks -> REP_1 -> Align Front */
#define PARAMETERS_TRACK_TRACKS_REP_1_ALIGN_FRONT_ADDR 0x00F9
#define PARAMETERS_TRACK_TRACKS_REP_1_ALIGN_FRONT_SIZE 8

/* Parameters -> Track -> Tracks -> REP_1 -> Align Back */
#define PARAMETERS_TRACK_TRACKS_REP_1_ALIGN_BACK_ADDR 0x0101
#define PARAMETERS_TRACK_TRACKS_REP_1_ALIGN_BACK_SIZE 8

/* Parameters -> Track -> Tracks -> REP_1 -> Stepper Position in Steps */
#define PARAMETERS_TRACK_TRACKS_REP_1_STEPPER_POSITION_IN_STEPS_ADDR 0x0109
#define PARAMETERS_TRACK_TRACKS_REP_1_STEPPER_POSITION_IN_STEPS_SIZE 4

/* Parameters -> Track -> Tracks -> REP_2 -> Description */
#define PARAMETERS_TRACK_TRACKS_REP_2_DESCRIPTION_ADDR 0x010D
#define PARAMETERS_TRACK_TRACKS_REP_2_DESCRIPTION_SIZE 25

/* Parameters -> Track -> Tracks -> REP_2 -> Short Name */
#define PARAMETERS_TRACK_TRACKS_REP_2_SHORT_NAME_ADDR 0x0126
#define PARAMETERS_TRACK_TRACKS_REP_2_SHORT_NAME_SIZE 5

/* Parameters -> Track -> Tracks -> REP_2 -> Align Front */
#define PARAMETERS_TRACK_TRACKS_REP_2_ALIGN_FRONT_ADDR 0x012B
#define PARAMETERS_TRACK_TRACKS_REP_2_ALIGN_FRONT_SIZE 8

/* Parameters -> Track -> Tracks -> REP_2 -> Align Back */
#define PARAMETERS_TRACK_TRACKS_REP_2_ALIGN_BACK_ADDR 0x0133
#define PARAMETERS_TRACK_TRACKS_REP_2_ALIGN_BACK_SIZE 8

/* Parameters -> Track -> Tracks -> REP_2 -> Stepper Position in Steps */
#define PARAMETERS_TRACK_TRACKS_REP_2_STEPPER_POSITION_IN_STEPS_ADDR 0x013B
#define PARAMETERS_TRACK_TRACKS_REP_2_STEPPER_POSITION_IN_STEPS_SIZE 4

/* Parameters -> Track -> Tracks -> REP_3 -> Description */
#define PARAMETERS_TRACK_TRACKS_REP_3_DESCRIPTION_ADDR 0x013F
#define PARAMETERS_TRACK_TRACKS_REP_3_DESCRIPTION_SIZE 25

/* Parameters -> Track -> Tracks -> REP_3 -> Short Name */
#define PARAMETERS_TRACK_TRACKS_REP_3_SHORT_NAME_ADDR 0x0158
#define PARAMETERS_TRACK_TRACKS_REP_3_SHORT_NAME_SIZE 5

/* Parameters -> Track -> Tracks -> REP_3 -> Align Front */
#define PARAMETERS_TRACK_TRACKS_REP_3_ALIGN_FRONT_ADDR 0x015D
#define PARAMETERS_TRACK_TRACKS_REP_3_ALIGN_FRONT_SIZE 8

/* Parameters -> Track -> Tracks -> REP_3 -> Align Back */
#define PARAMETERS_TRACK_TRACKS_REP_3_ALIGN_BACK_ADDR 0x0165
#define PARAMETERS_TRACK_TRACKS_REP_3_ALIGN_BACK_SIZE 8

/* Parameters -> Track -> Tracks -> REP_3 -> Stepper Position in Steps */
#define PARAMETERS_TRACK_TRACKS_REP_3_STEPPER_POSITION_IN_STEPS_ADDR 0x016D
#define PARAMETERS_TRACK_TRACKS_REP_3_STEPPER_POSITION_IN_STEPS_SIZE 4

/* Parameters -> Track -> Tracks -> REP_4 -> Description */
#define PARAMETERS_TRACK_TRACKS_REP_4_DESCRIPTION_ADDR 0x0171
#define PARAMETERS_TRACK_TRACKS_REP_4_DESCRIPTION_SIZE 25

/* Parameters -> Track -> Tracks -> REP_4 -> Short Name */
#define PARAMETERS_TRACK_TRACKS_REP_4_SHORT_NAME_ADDR 0x018A
#define PARAMETERS_TRACK_TRACKS_REP_4_SHORT_NAME_SIZE 5

/* Parameters -> Track -> Tracks -> REP_4 -> Align Front */
#define PARAMETERS_TRACK_TRACKS_REP_4_ALIGN_FRONT_ADDR 0x018F
#define PARAMETERS_TRACK_TRACKS_REP_4_ALIGN_FRONT_SIZE 8

/* Parameters -> Track -> Tracks -> REP_4 -> Align Back */
#define PARAMETERS_TRACK_TRACKS_REP_4_ALIGN_BACK_ADDR 0x0197
#define PARAMETERS_TRACK_TRACKS_REP_4_ALIGN_BACK_SIZE 8

/* Parameters -> Track -> Tracks -> REP_4 -> Stepper Position in Steps */
#define PARAMETERS_TRACK_TRACKS_REP_4_STEPPER_POSITION_IN_STEPS_ADDR 0x019F
#define PARAMETERS_TRACK_TRACKS_REP_4_STEPPER_POSITION_IN_STEPS_SIZE 4

/* Parameters -> Track -> Tracks -> REP_5 -> Description */
#define PARAMETERS_TRACK_TRACKS_REP_5_DESCRIPTION_ADDR 0x01A3
#define PARAMETERS_TRACK_TRACKS_REP_5_DESCRIPTION_SIZE 25

/* Parameters -> Track -> Tracks -> REP_5 -> Short Name */
#define PARAMETERS_TRACK_TRACKS_REP_5_SHORT_NAME_ADDR 0x01BC
#define PARAMETERS_TRACK_TRACKS_REP_5_SHORT_NAME_SIZE 5

/* Parameters -> Track -> Tracks -> REP_5 -> Align Front */
#define PARAMETERS_TRACK_TRACKS_REP_5_ALIGN_FRONT_ADDR 0x01C1
#define PARAMETERS_TRACK_TRACKS_REP_5_ALIGN_FRONT_SIZE 8

/* Parameters -> Track -> Tracks -> REP_5 -> Align Back */
#define PARAMETERS_TRACK_TRACKS_REP_5_ALIGN_BACK_ADDR 0x01C9
#define PARAMETERS_TRACK_TRACKS_REP_5_ALIGN_BACK_SIZE 8

/* Parameters -> Track -> Tracks -> REP_5 -> Stepper Position in Steps */
#define PARAMETERS_TRACK_TRACKS_REP_5_STEPPER_POSITION_IN_STEPS_ADDR 0x01D1
#define PARAMETERS_TRACK_TRACKS_REP_5_STEPPER_POSITION_IN_STEPS_SIZE 4

/* Parameters -> Track -> Tracks -> REP_6 -> Description */
#define PARAMETERS_TRACK_TRACKS_REP_6_DESCRIPTION_ADDR 0x01D5
#define PARAMETERS_TRACK_TRACKS_REP_6_DESCRIPTION_SIZE 25

/* Parameters -> Track -> Tracks -> REP_6 -> Short Name */
#define PARAMETERS_TRACK_TRACKS_REP_6_SHORT_NAME_ADDR 0x01EE
#define PARAMETERS_TRACK_TRACKS_REP_6_SHORT_NAME_SIZE 5

/* Parameters -> Track -> Tracks -> REP_6 -> Align Front */
#define PARAMETERS_TRACK_TRACKS_REP_6_ALIGN_FRONT_ADDR 0x01F3
#define PARAMETERS_TRACK_TRACKS_REP_6_ALIGN_FRONT_SIZE 8

/* Parameters -> Track -> Tracks -> REP_6 -> Align Back */
#define PARAMETERS_TRACK_TRACKS_REP_6_ALIGN_BACK_ADDR 0x01FB
#define PARAMETERS_TRACK_TRACKS_REP_6_ALIGN_BACK_SIZE 8

/* Parameters -> Track -> Tracks -> REP_6 -> Stepper Position in Steps */
#define PARAMETERS_TRACK_TRACKS_REP_6_STEPPER_POSITION_IN_STEPS_ADDR 0x0203
#define PARAMETERS_TRACK_TRACKS_REP_6_STEPPER_POSITION_IN_STEPS_SIZE 4

/* Parameters -> Track -> Tracks -> REP_7 -> Description */
#define PARAMETERS_TRACK_TRACKS_REP_7_DESCRIPTION_ADDR 0x0207
#define PARAMETERS_TRACK_TRACKS_REP_7_DESCRIPTION_SIZE 25

/* Parameters -> Track -> Tracks -> REP_7 -> Short Name */
#define PARAMETERS_TRACK_TRACKS_REP_7_SHORT_NAME_ADDR 0x0220
#define PARAMETERS_TRACK_TRACKS_REP_7_SHORT_NAME_SIZE 5

/* Parameters -> Track -> Tracks -> REP_7 -> Align Front */
#define PARAMETERS_TRACK_TRACKS_REP_7_ALIGN_FRONT_ADDR 0x0225
#define PARAMETERS_TRACK_TRACKS_REP_7_ALIGN_FRONT_SIZE 8

/* Parameters -> Track -> Tracks -> REP_7 -> Align Back */
#define PARAMETERS_TRACK_TRACKS_REP_7_ALIGN_BACK_ADDR 0x022D
#define PARAMETERS_TRACK_TRACKS_REP_7_ALIGN_BACK_SIZE 8

/* Parameters -> Track -> Tracks -> REP_7 -> Stepper Position in Steps */
#define PARAMETERS_TRACK_TRACKS_REP_7_STEPPER_POSITION_IN_STEPS_ADDR 0x0235
#define PARAMETERS_TRACK_TRACKS_REP_7_STEPPER_POSITION_IN_STEPS_SIZE 4

/* Parameters -> Track -> Tracks -> REP_8 -> Description */
#define PARAMETERS_TRACK_TRACKS_REP_8_DESCRIPTION_ADDR 0x0239
#define PARAMETERS_TRACK_TRACKS_REP_8_DESCRIPTION_SIZE 25

/* Parameters -> Track -> Tracks -> REP_8 -> Short Name */
#define PARAMETERS_TRACK_TRACKS_REP_8_SHORT_NAME_ADDR 0x0252
#define PARAMETERS_TRACK_TRACKS_REP_8_SHORT_NAME_SIZE 5

/* Parameters -> Track -> Tracks -> REP_8 -> Align Front */
#define PARAMETERS_TRACK_TRACKS_REP_8_ALIGN_FRONT_ADDR 0x0257
#define PARAMETERS_TRACK_TRACKS_REP_8_ALIGN_FRONT_SIZE 8

/* Parameters -> Track -> Tracks -> REP_8 -> Align Back */
#define PARAMETERS_TRACK_TRACKS_REP_8_ALIGN_BACK_ADDR 0x025F
#define PARAMETERS_TRACK_TRACKS_REP_8_ALIGN_BACK_SIZE 8

/* Parameters -> Track -> Tracks -> REP_8 -> Stepper Position in Steps */
#define PARAMETERS_TRACK_TRACKS_REP_8_STEPPER_POSITION_IN_STEPS_ADDR 0x0267
#define PARAMETERS_TRACK_TRACKS_REP_8_STEPPER_POSITION_IN_STEPS_SIZE 4

/* Parameters -> Track -> Tracks -> REP_9 -> Description */
#define PARAMETERS_TRACK_TRACKS_REP_9_DESCRIPTION_ADDR 0x026B
#define PARAMETERS_TRACK_TRACKS_REP_9_DESCRIPTION_SIZE 25

/* Parameters -> Track -> Tracks -> REP_9 -> Short Name */
#define PARAMETERS_TRACK_TRACKS_REP_9_SHORT_NAME_ADDR 0x0284
#define PARAMETERS_TRACK_TRACKS_REP_9_SHORT_NAME_SIZE 5

/* Parameters -> Track -> Tracks -> REP_9 -> Align Front */
#define PARAMETERS_TRACK_TRACKS_REP_9_ALIGN_FRONT_ADDR 0x0289
#define PARAMETERS_TRACK_TRACKS_REP_9_ALIGN_FRONT_SIZE 8

/* Parameters -> Track -> Tracks -> REP_9 -> Align Back */
#define PARAMETERS_TRACK_TRACKS_REP_9_ALIGN_BACK_ADDR 0x0291
#define PARAMETERS_TRACK_TRACKS_REP_9_ALIGN_BACK_SIZE 8

/* Parameters -> Track -> Tracks -> REP_9 -> Stepper Position in Steps */
#define PARAMETERS_TRACK_TRACKS_REP_9_STEPPER_POSITION_IN_STEPS_ADDR 0x0299
#define PARAMETERS_TRACK_TRACKS_REP_9_STEPPER_POSITION_IN_STEPS_SIZE 4

/* Parameters -> Track -> Tracks -> REP_10 -> Description */
#define PARAMETERS_TRACK_TRACKS_REP_10_DESCRIPTION_ADDR 0x029D
#define PARAMETERS_TRACK_TRACKS_REP_10_DESCRIPTION_SIZE 25

/* Parameters -> Track -> Tracks -> REP_10 -> Short Name */
#define PARAMETERS_TRACK_TRACKS_REP_10_SHORT_NAME_ADDR 0x02B6
#define PARAMETERS_TRACK_TRACKS_REP_10_SHORT_NAME_SIZE 5

/* Parameters -> Track -> Tracks -> REP_10 -> Align Front */
#define PARAMETERS_TRACK_TRACKS_REP_10_ALIGN_FRONT_ADDR 0x02BB
#define PARAMETERS_TRACK_TRACKS_REP_10_ALIGN_FRONT_SIZE 8

/* Parameters -> Track -> Tracks -> REP_10 -> Align Back */
#define PARAMETERS_TRACK_TRACKS_REP_10_ALIGN_BACK_ADDR 0x02C3
#define PARAMETERS_TRACK_TRACKS_REP_10_ALIGN_BACK_SIZE 8

/* Parameters -> Track -> Tracks -> REP_10 -> Stepper Position in Steps */
#define PARAMETERS_TRACK_TRACKS_REP_10_STEPPER_POSITION_IN_STEPS_ADDR 0x02CB
#define PARAMETERS_TRACK_TRACKS_REP_10_STEPPER_POSITION_IN_STEPS_SIZE 4

/* Parameters -> Track -> Tracks -> REP_11 -> Description */
#define PARAMETERS_TRACK_TRACKS_REP_11_DESCRIPTION_ADDR 0x02CF
#define PARAMETERS_TRACK_TRACKS_REP_11_DESCRIPTION_SIZE 25

/* Parameters -> Track -> Tracks -> REP_11 -> Short Name */
#define PARAMETERS_TRACK_TRACKS_REP_11_SHORT_NAME_ADDR 0x02E8
#define PARAMETERS_TRACK_TRACKS_REP_11_SHORT_NAME_SIZE 5

/* Parameters -> Track -> Tracks -> REP_11 -> Align Front */
#define PARAMETERS_TRACK_TRACKS_REP_11_ALIGN_FRONT_ADDR 0x02ED
#define PARAMETERS_TRACK_TRACKS_REP_11_ALIGN_FRONT_SIZE 8

/* Parameters -> Track -> Tracks -> REP_11 -> Align Back */
#define PARAMETERS_TRACK_TRACKS_REP_11_ALIGN_BACK_ADDR 0x02F5
#define PARAMETERS_TRACK_TRACKS_REP_11_ALIGN_BACK_SIZE 8

/* Parameters -> Track -> Tracks -> REP_11 -> Stepper Position in Steps */
#define PARAMETERS_TRACK_TRACKS_REP_11_STEPPER_POSITION_IN_STEPS_ADDR 0x02FD
#define PARAMETERS_TRACK_TRACKS_REP_11_STEPPER_POSITION_IN_STEPS_SIZE 4

/* Parameters -> Track -> Tracks -> REP_12 -> Description */
#define PARAMETERS_TRACK_TRACKS_REP_12_DESCRIPTION_ADDR 0x0301
#define PARAMETERS_TRACK_TRACKS_REP_12_DESCRIPTION_SIZE 25

/* Parameters -> Track -> Tracks -> REP_12 -> Short Name */
#define PARAMETERS_TRACK_TRACKS_REP_12_SHORT_NAME_ADDR 0x031A
#define PARAMETERS_TRACK_TRACKS_REP_12_SHORT_NAME_SIZE 5

/* Parameters -> Track -> Tracks -> REP_12 -> Align Front */
#define PARAMETERS_TRACK_TRACKS_REP_12_ALIGN_FRONT_ADDR 0x031F
#define PARAMETERS_TRACK_TRACKS_REP_12_ALIGN_FRONT_SIZE 8

/* Parameters -> Track -> Tracks -> REP_12 -> Align Back */
#define PARAMETERS_TRACK_TRACKS_REP_12_ALIGN_BACK_ADDR 0x0327
#define PARAMETERS_TRACK_TRACKS_REP_12_ALIGN_BACK_SIZE 8

/* Parameters -> Track -> Tracks -> REP_12 -> Stepper Position in Steps */
#define PARAMETERS_TRACK_TRACKS_REP_12_STEPPER_POSITION_IN_STEPS_ADDR 0x032F
#define PARAMETERS_TRACK_TRACKS_REP_12_STEPPER_POSITION_IN_STEPS_SIZE 4

/* Parameters -> Track -> Tracks -> REP_13 -> Description */
#define PARAMETERS_TRACK_TRACKS_REP_13_DESCRIPTION_ADDR 0x0333
#define PARAMETERS_TRACK_TRACKS_REP_13_DESCRIPTION_SIZE 25

/* Parameters -> Track -> Tracks -> REP_13 -> Short Name */
#define PARAMETERS_TRACK_TRACKS_REP_13_SHORT_NAME_ADDR 0x034C
#define PARAMETERS_TRACK_TRACKS_REP_13_SHORT_NAME_SIZE 5

/* Parameters -> Track -> Tracks -> REP_13 -> Align Front */
#define PARAMETERS_TRACK_TRACKS_REP_13_ALIGN_FRONT_ADDR 0x0351
#define PARAMETERS_TRACK_TRACKS_REP_13_ALIGN_FRONT_SIZE 8

/* Parameters -> Track -> Tracks -> REP_13 -> Align Back */
#define PARAMETERS_TRACK_TRACKS_REP_13_ALIGN_BACK_ADDR 0x0359
#define PARAMETERS_TRACK_TRACKS_REP_13_ALIGN_BACK_SIZE 8

/* Parameters -> Track -> Tracks -> REP_13 -> Stepper Position in Steps */
#define PARAMETERS_TRACK_TRACKS_REP_13_STEPPER_POSITION_IN_STEPS_ADDR 0x0361
#define PARAMETERS_TRACK_TRACKS_REP_13_STEPPER_POSITION_IN_STEPS_SIZE 4

/* Parameters -> Track -> Tracks -> REP_14 -> Description */
#define PARAMETERS_TRACK_TRACKS_REP_14_DESCRIPTION_ADDR 0x0365
#define PARAMETERS_TRACK_TRACKS_REP_14_DESCRIPTION_SIZE 25

/* Parameters -> Track -> Tracks -> REP_14 -> Short Name */
#define PARAMETERS_TRACK_TRACKS_REP_14_SHORT_NAME_ADDR 0x037E
#define PARAMETERS_TRACK_TRACKS_REP_14_SHORT_NAME_SIZE 5

/* Parameters -> Track -> Tracks -> REP_14 -> Align Front */
#define PARAMETERS_TRACK_TRACKS_REP_14_ALIGN_FRONT_ADDR 0x0383
#define PARAMETERS_TRACK_TRACKS_REP_14_ALIGN_FRONT_SIZE 8

/* Parameters -> Track -> Tracks -> REP_14 -> Align Back */
#define PARAMETERS_TRACK_TRACKS_REP_14_ALIGN_BACK_ADDR 0x038B
#define PARAMETERS_TRACK_TRACKS_REP_14_ALIGN_BACK_SIZE 8

/* Parameters -> Track -> Tracks -> REP_14 -> Stepper Position in Steps */
#define PARAMETERS_TRACK_TRACKS_REP_14_STEPPER_POSITION_IN_STEPS_ADDR 0x0393
#define PARAMETERS_TRACK_TRACKS_REP_14_STEPPER_POSITION_IN_STEPS_SIZE 4

/* Parameters -> Track -> Tracks -> REP_15 -> Description */
#define PARAMETERS_TRACK_TRACKS_REP_15_DESCRIPTION_ADDR 0x0397
#define PARAMETERS_TRACK_TRACKS_REP_15_DESCRIPTION_SIZE 25

/* Parameters -> Track -> Tracks -> REP_15 -> Short Name */
#define PARAMETERS_TRACK_TRACKS_REP_15_SHORT_NAME_ADDR 0x03B0
#define PARAMETERS_TRACK_TRACKS_REP_15_SHORT_NAME_SIZE 5

/* Parameters -> Track -> Tracks -> REP_15 -> Align Front */
#define PARAMETERS_TRACK_TRACKS_REP_15_ALIGN_FRONT_ADDR 0x03B5
#define PARAMETERS_TRACK_TRACKS_REP_15_ALIGN_FRONT_SIZE 8

/* Parameters -> Track -> Tracks -> REP_15 -> Align Back */
#define PARAMETERS_TRACK_TRACKS_REP_15_ALIGN_BACK_ADDR 0x03BD
#define PARAMETERS_TRACK_TRACKS_REP_15_ALIGN_BACK_SIZE 8

/* Parameters -> Track -> Tracks -> REP_15 -> Stepper Position in Steps */
#define PARAMETERS_TRACK_TRACKS_REP_15_STEPPER_POSITION_IN_STEPS_ADDR 0x03C5
#define PARAMETERS_TRACK_TRACKS_REP_15_STEPPER_POSITION_IN_STEPS_SIZE 4

/* Parameters -> Track -> Tracks -> REP_16 -> Description */
#define PARAMETERS_TRACK_TRACKS_REP_16_DESCRIPTION_ADDR 0x03C9
#define PARAMETERS_TRACK_TRACKS_REP_16_DESCRIPTION_SIZE 25

/* Parameters -> Track -> Tracks -> REP_16 -> Short Name */
#define PARAMETERS_TRACK_TRACKS_REP_16_SHORT_NAME_ADDR 0x03E2
#define PARAMETERS_TRACK_TRACKS_REP_16_SHORT_NAME_SIZE 5

/* Parameters -> Track -> Tracks -> REP_16 -> Align Front */
#define PARAMETERS_TRACK_TRACKS_REP_16_ALIGN_FRONT_ADDR 0x03E7
#define PARAMETERS_TRACK_TRACKS_REP_16_ALIGN_FRONT_SIZE 8

/* Parameters -> Track -> Tracks -> REP_16 -> Align Back */
#define PARAMETERS_TRACK_TRACKS_REP_16_ALIGN_BACK_ADDR 0x03EF
#define PARAMETERS_TRACK_TRACKS_REP_16_ALIGN_BACK_SIZE 8

/* Parameters -> Track -> Tracks -> REP_16 -> Stepper Position in Steps */
#define PARAMETERS_TRACK_TRACKS_REP_16_STEPPER_POSITION_IN_STEPS_ADDR 0x03F7
#define PARAMETERS_TRACK_TRACKS_REP_16_STEPPER_POSITION_IN_STEPS_SIZE 4

/* Parameters -> Track -> Tracks -> REP_17 -> Description */
#define PARAMETERS_TRACK_TRACKS_REP_17_DESCRIPTION_ADDR 0x03FB
#define PARAMETERS_TRACK_TRACKS_REP_17_DESCRIPTION_SIZE 25

/* Parameters -> Track -> Tracks -> REP_17 -> Short Name */
#define PARAMETERS_TRACK_TRACKS_REP_17_SHORT_NAME_ADDR 0x0414
#define PARAMETERS_TRACK_TRACKS_REP_17_SHORT_NAME_SIZE 5

/* Parameters -> Track -> Tracks -> REP_17 -> Align Front */
#define PARAMETERS_TRACK_TRACKS_REP_17_ALIGN_FRONT_ADDR 0x0419
#define PARAMETERS_TRACK_TRACKS_REP_17_ALIGN_FRONT_SIZE 8

/* Parameters -> Track -> Tracks -> REP_17 -> Align Back */
#define PARAMETERS_TRACK_TRACKS_REP_17_ALIGN_BACK_ADDR 0x0421
#define PARAMETERS_TRACK_TRACKS_REP_17_ALIGN_BACK_SIZE 8

/* Parameters -> Track -> Tracks -> REP_17 -> Stepper Position in Steps */
#define PARAMETERS_TRACK_TRACKS_REP_17_STEPPER_POSITION_IN_STEPS_ADDR 0x0429
#define PARAMETERS_TRACK_TRACKS_REP_17_STEPPER_POSITION_IN_STEPS_SIZE 4

/* Parameters -> Track -> Tracks -> REP_18 -> Description */
#define PARAMETERS_TRACK_TRACKS_REP_18_DESCRIPTION_ADDR 0x042D
#define PARAMETERS_TRACK_TRACKS_REP_18_DESCRIPTION_SIZE 25

/* Parameters -> Track -> Tracks -> REP_18 -> Short Name */
#define PARAMETERS_TRACK_TRACKS_REP_18_SHORT_NAME_ADDR 0x0446
#define PARAMETERS_TRACK_TRACKS_REP_18_SHORT_NAME_SIZE 5

/* Parameters -> Track -> Tracks -> REP_18 -> Align Front */
#define PARAMETERS_TRACK_TRACKS_REP_18_ALIGN_FRONT_ADDR 0x044B
#define PARAMETERS_TRACK_TRACKS_REP_18_ALIGN_FRONT_SIZE 8

/* Parameters -> Track -> Tracks -> REP_18 -> Align Back */
#define PARAMETERS_TRACK_TRACKS_REP_18_ALIGN_BACK_ADDR 0x0453
#define PARAMETERS_TRACK_TRACKS_REP_18_ALIGN_BACK_SIZE 8

/* Parameters -> Track -> Tracks -> REP_18 -> Stepper Position in Steps */
#define PARAMETERS_TRACK_TRACKS_REP_18_STEPPER_POSITION_IN_STEPS_ADDR 0x045B
#define PARAMETERS_TRACK_TRACKS_REP_18_STEPPER_POSITION_IN_STEPS_SIZE 4

/* Parameters -> Track -> Tracks -> REP_19 -> Description */
#define PARAMETERS_TRACK_TRACKS_REP_19_DESCRIPTION_ADDR 0x045F
#define PARAMETERS_TRACK_TRACKS_REP_19_DESCRIPTION_SIZE 25

/* Parameters -> Track -> Tracks -> REP_19 -> Short Name */
#define PARAMETERS_TRACK_TRACKS_REP_19_SHORT_NAME_ADDR 0x0478
#define PARAMETERS_TRACK_TRACKS_REP_19_SHORT_NAME_SIZE 5

/* Parameters -> Track -> Tracks -> REP_19 -> Align Front */
#define PARAMETERS_TRACK_TRACKS_REP_19_ALIGN_FRONT_ADDR 0x047D
#define PARAMETERS_TRACK_TRACKS_REP_19_ALIGN_FRONT_SIZE 8

/* Parameters -> Track -> Tracks -> REP_19 -> Align Back */
#define PARAMETERS_TRACK_TRACKS_REP_19_ALIGN_BACK_ADDR 0x0485
#define PARAMETERS_TRACK_TRACKS_REP_19_ALIGN_BACK_SIZE 8

/* Parameters -> Track -> Tracks -> REP_19 -> Stepper Position in Steps */
#define PARAMETERS_TRACK_TRACKS_REP_19_STEPPER_POSITION_IN_STEPS_ADDR 0x048D
#define PARAMETERS_TRACK_TRACKS_REP_19_STEPPER_POSITION_IN_STEPS_SIZE 4

/* Parameters -> Doors -> Active Doors */
#define PARAMETERS_DOORS_ACTIVE_DOORS_ADDR 0x0491
#define PARAMETERS_DOORS_ACTIVE_DOORS_SIZE 1

/* Parameters -> Doors -> Open All Doors */
#define PARAMETERS_DOORS_OPEN_ALL_DOORS_ADDR 0x0492
#define PARAMETERS_DOORS_OPEN_ALL_DOORS_SIZE 8

/* Parameters -> Doors -> Close All Doors */
#define PARAMETERS_DOORS_CLOSE_ALL_DOORS_ADDR 0x049A
#define PARAMETERS_DOORS_CLOSE_ALL_DOORS_SIZE 8

/* Parameters -> Doors -> Door -> REP_0 -> Description */
#define PARAMETERS_DOORS_DOOR_REP_0_DESCRIPTION_ADDR 0x04A2
#define PARAMETERS_DOORS_DOOR_REP_0_DESCRIPTION_SIZE 16

/* Parameters -> Doors -> Door -> REP_0 -> Short Name */
#define PARAMETERS_DOORS_DOOR_REP_0_SHORT_NAME_ADDR 0x04B2
#define PARAMETERS_DOORS_DOOR_REP_0_SHORT_NAME_SIZE 5

/* Parameters -> Doors -> Door -> REP_0 -> Toggle Door */
#define PARAMETERS_DOORS_DOOR_REP_0_TOGGLE_DOOR_ADDR 0x04B7
#define PARAMETERS_DOORS_DOOR_REP_0_TOGGLE_DOOR_SIZE 8

/* Parameters -> Doors -> Door -> REP_0 -> Track Number */
#define PARAMETERS_DOORS_DOOR_REP_0_TRACK_NUMBER_ADDR 0x04BF
#define PARAMETERS_DOORS_DOOR_REP_0_TRACK_NUMBER_SIZE 1

/* Parameters -> Doors -> Door -> REP_1 -> Description */
#define PARAMETERS_DOORS_DOOR_REP_1_DESCRIPTION_ADDR 0x04C0
#define PARAMETERS_DOORS_DOOR_REP_1_DESCRIPTION_SIZE 16

/* Parameters -> Doors -> Door -> REP_1 -> Short Name */
#define PARAMETERS_DOORS_DOOR_REP_1_SHORT_NAME_ADDR 0x04D0
#define PARAMETERS_DOORS_DOOR_REP_1_SHORT_NAME_SIZE 5

/* Parameters -> Doors -> Door -> REP_1 -> Toggle Door */
#define PARAMETERS_DOORS_DOOR_REP_1_TOGGLE_DOOR_ADDR 0x04D5
#define PARAMETERS_DOORS_DOOR_REP_1_TOGGLE_DOOR_SIZE 8

/* Parameters -> Doors -> Door -> REP_1 -> Track Number */
#define PARAMETERS_DOORS_DOOR_REP_1_TRACK_NUMBER_ADDR 0x04DD
#define PARAMETERS_DOORS_DOOR_REP_1_TRACK_NUMBER_SIZE 1

/* Parameters -> Doors -> Door -> REP_2 -> Description */
#define PARAMETERS_DOORS_DOOR_REP_2_DESCRIPTION_ADDR 0x04DE
#define PARAMETERS_DOORS_DOOR_REP_2_DESCRIPTION_SIZE 16

/* Parameters -> Doors -> Door -> REP_2 -> Short Name */
#define PARAMETERS_DOORS_DOOR_REP_2_SHORT_NAME_ADDR 0x04EE
#define PARAMETERS_DOORS_DOOR_REP_2_SHORT_NAME_SIZE 5

/* Parameters -> Doors -> Door -> REP_2 -> Toggle Door */
#define PARAMETERS_DOORS_DOOR_REP_2_TOGGLE_DOOR_ADDR 0x04F3
#define PARAMETERS_DOORS_DOOR_REP_2_TOGGLE_DOOR_SIZE 8

/* Parameters -> Doors -> Door -> REP_2 -> Track Number */
#define PARAMETERS_DOORS_DOOR_REP_2_TRACK_NUMBER_ADDR 0x04FB
#define PARAMETERS_DOORS_DOOR_REP_2_TRACK_NUMBER_SIZE 1

/* Parameters -> Doors -> Door -> REP_3 -> Description */
#define PARAMETERS_DOORS_DOOR_REP_3_DESCRIPTION_ADDR 0x04FC
#define PARAMETERS_DOORS_DOOR_REP_3_DESCRIPTION_SIZE 16

/* Parameters -> Doors -> Door -> REP_3 -> Short Name */
#define PARAMETERS_DOORS_DOOR_REP_3_SHORT_NAME_ADDR 0x050C
#define PARAMETERS_DOORS_DOOR_REP_3_SHORT_NAME_SIZE 5

/* Parameters -> Doors -> Door -> REP_3 -> Toggle Door */
#define PARAMETERS_DOORS_DOOR_REP_3_TOGGLE_DOOR_ADDR 0x0511
#define PARAMETERS_DOORS_DOOR_REP_3_TOGGLE_DOOR_SIZE 8

/* Parameters -> Doors -> Door -> REP_3 -> Track Number */
#define PARAMETERS_DOORS_DOOR_REP_3_TRACK_NUMBER_ADDR 0x0519
#define PARAMETERS_DOORS_DOOR_REP_3_TRACK_NUMBER_SIZE 1

/* Parameters -> Doors -> Door -> REP_4 -> Description */
#define PARAMETERS_DOORS_DOOR_REP_4_DESCRIPTION_ADDR 0x051A
#define PARAMETERS_DOORS_DOOR_REP_4_DESCRIPTION_SIZE 16

/* Parameters -> Doors -> Door -> REP_4 -> Short Name */
#define PARAMETERS_DOORS_DOOR_REP_4_SHORT_NAME_ADDR 0x052A
#define PARAMETERS_DOORS_DOOR_REP_4_SHORT_NAME_SIZE 5

/* Parameters -> Doors -> Door -> REP_4 -> Toggle Door */
#define PARAMETERS_DOORS_DOOR_REP_4_TOGGLE_DOOR_ADDR 0x052F
#define PARAMETERS_DOORS_DOOR_REP_4_TOGGLE_DOOR_SIZE 8

/* Parameters -> Doors -> Door -> REP_4 -> Track Number */
#define PARAMETERS_DOORS_DOOR_REP_4_TRACK_NUMBER_ADDR 0x0537
#define PARAMETERS_DOORS_DOOR_REP_4_TRACK_NUMBER_SIZE 1

/* Parameters -> Doors -> Door -> REP_5 -> Description */
#define PARAMETERS_DOORS_DOOR_REP_5_DESCRIPTION_ADDR 0x0538
#define PARAMETERS_DOORS_DOOR_REP_5_DESCRIPTION_SIZE 16

/* Parameters -> Doors -> Door -> REP_5 -> Short Name */
#define PARAMETERS_DOORS_DOOR_REP_5_SHORT_NAME_ADDR 0x0548
#define PARAMETERS_DOORS_DOOR_REP_5_SHORT_NAME_SIZE 5

/* Parameters -> Doors -> Door -> REP_5 -> Toggle Door */
#define PARAMETERS_DOORS_DOOR_REP_5_TOGGLE_DOOR_ADDR 0x054D
#define PARAMETERS_DOORS_DOOR_REP_5_TOGGLE_DOOR_SIZE 8

/* Parameters -> Doors -> Door -> REP_5 -> Track Number */
#define PARAMETERS_DOORS_DOOR_REP_5_TRACK_NUMBER_ADDR 0x0555
#define PARAMETERS_DOORS_DOOR_REP_5_TRACK_NUMBER_SIZE 1

/* Parameters -> Doors -> Door -> REP_6 -> Description */
#define PARAMETERS_DOORS_DOOR_REP_6_DESCRIPTION_ADDR 0x0556
#define PARAMETERS_DOORS_DOOR_REP_6_DESCRIPTION_SIZE 16

/* Parameters -> Doors -> Door -> REP_6 -> Short Name */
#define PARAMETERS_DOORS_DOOR_REP_6_SHORT_NAME_ADDR 0x0566
#define PARAMETERS_DOORS_DOOR_REP_6_SHORT_NAME_SIZE 5

/* Parameters -> Doors -> Door -> REP_6 -> Toggle Door */
#define PARAMETERS_DOORS_DOOR_REP_6_TOGGLE_DOOR_ADDR 0x056B
#define PARAMETERS_DOORS_DOOR_REP_6_TOGGLE_DOOR_SIZE 8

/* Parameters -> Doors -> Door -> REP_6 -> Track Number */
#define PARAMETERS_DOORS_DOOR_REP_6_TRACK_NUMBER_ADDR 0x0573
#define PARAMETERS_DOORS_DOOR_REP_6_TRACK_NUMBER_SIZE 1

/* Parameters -> Doors -> Door -> REP_7 -> Description */
#define PARAMETERS_DOORS_DOOR_REP_7_DESCRIPTION_ADDR 0x0574
#define PARAMETERS_DOORS_DOOR_REP_7_DESCRIPTION_SIZE 16

/* Parameters -> Doors -> Door -> REP_7 -> Short Name */
#define PARAMETERS_DOORS_DOOR_REP_7_SHORT_NAME_ADDR 0x0584
#define PARAMETERS_DOORS_DOOR_REP_7_SHORT_NAME_SIZE 5

/* Parameters -> Doors -> Door -> REP_7 -> Toggle Door */
#define PARAMETERS_DOORS_DOOR_REP_7_TOGGLE_DOOR_ADDR 0x0589
#define PARAMETERS_DOORS_DOOR_REP_7_TOGGLE_DOOR_SIZE 8

/* Parameters -> Doors -> Door -> REP_7 -> Track Number */
#define PARAMETERS_DOORS_DOOR_REP_7_TRACK_NUMBER_ADDR 0x0591
#define PARAMETERS_DOORS_DOOR_REP_7_TRACK_NUMBER_SIZE 1

/* Parameters -> Doors -> Door -> REP_8 -> Description */
#define PARAMETERS_DOORS_DOOR_REP_8_DESCRIPTION_ADDR 0x0592
#define PARAMETERS_DOORS_DOOR_REP_8_DESCRIPTION_SIZE 16

/* Parameters -> Doors -> Door -> REP_8 -> Short Name */
#define PARAMETERS_DOORS_DOOR_REP_8_SHORT_NAME_ADDR 0x05A2
#define PARAMETERS_DOORS_DOOR_REP_8_SHORT_NAME_SIZE 5

/* Parameters -> Doors -> Door -> REP_8 -> Toggle Door */
#define PARAMETERS_DOORS_DOOR_REP_8_TOGGLE_DOOR_ADDR 0x05A7
#define PARAMETERS_DOORS_DOOR_REP_8_TOGGLE_DOOR_SIZE 8

/* Parameters -> Doors -> Door -> REP_8 -> Track Number */
#define PARAMETERS_DOORS_DOOR_REP_8_TRACK_NUMBER_ADDR 0x05AF
#define PARAMETERS_DOORS_DOOR_REP_8_TRACK_NUMBER_SIZE 1

/* Parameters -> Doors -> Door -> REP_9 -> Description */
#define PARAMETERS_DOORS_DOOR_REP_9_DESCRIPTION_ADDR 0x05B0
#define PARAMETERS_DOORS_DOOR_REP_9_DESCRIPTION_SIZE 16

/* Parameters -> Doors -> Door -> REP_9 -> Short Name */
#define PARAMETERS_DOORS_DOOR_REP_9_SHORT_NAME_ADDR 0x05C0
#define PARAMETERS_DOORS_DOOR_REP_9_SHORT_NAME_SIZE 5

/* Parameters -> Doors -> Door -> REP_9 -> Toggle Door */
#define PARAMETERS_DOORS_DOOR_REP_9_TOGGLE_DOOR_ADDR 0x05C5
#define PARAMETERS_DOORS_DOOR_REP_9_TOGGLE_DOOR_SIZE 8

/* Parameters -> Doors -> Door -> REP_9 -> Track Number */
#define PARAMETERS_DOORS_DOOR_REP_9_TRACK_NUMBER_ADDR 0x05CD
#define PARAMETERS_DOORS_DOOR_REP_9_TRACK_NUMBER_SIZE 1

/* Parameters -> Doors -> Door -> REP_10 -> Description */
#define PARAMETERS_DOORS_DOOR_REP_10_DESCRIPTION_ADDR 0x05CE
#define PARAMETERS_DOORS_DOOR_REP_10_DESCRIPTION_SIZE 16

/* Parameters -> Doors -> Door -> REP_10 -> Short Name */
#define PARAMETERS_DOORS_DOOR_REP_10_SHORT_NAME_ADDR 0x05DE
#define PARAMETERS_DOORS_DOOR_REP_10_SHORT_NAME_SIZE 5

/* Parameters -> Doors -> Door -> REP_10 -> Toggle Door */
#define PARAMETERS_DOORS_DOOR_REP_10_TOGGLE_DOOR_ADDR 0x05E3
#define PARAMETERS_DOORS_DOOR_REP_10_TOGGLE_DOOR_SIZE 8

/* Parameters -> Doors -> Door -> REP_10 -> Track Number */
#define PARAMETERS_DOORS_DOOR_REP_10_TRACK_NUMBER_ADDR 0x05EB
#define PARAMETERS_DOORS_DOOR_REP_10_TRACK_NUMBER_SIZE 1

/* Parameters -> Doors -> Door -> REP_11 -> Description */
#define PARAMETERS_DOORS_DOOR_REP_11_DESCRIPTION_ADDR 0x05EC
#define PARAMETERS_DOORS_DOOR_REP_11_DESCRIPTION_SIZE 16

/* Parameters -> Doors -> Door -> REP_11 -> Short Name */
#define PARAMETERS_DOORS_DOOR_REP_11_SHORT_NAME_ADDR 0x05FC
#define PARAMETERS_DOORS_DOOR_REP_11_SHORT_NAME_SIZE 5

/* Parameters -> Doors -> Door -> REP_11 -> Toggle Door */
#define PARAMETERS_DOORS_DOOR_REP_11_TOGGLE_DOOR_ADDR 0x0601
#define PARAMETERS_DOORS_DOOR_REP_11_TOGGLE_DOOR_SIZE 8

/* Parameters -> Doors -> Door -> REP_11 -> Track Number */
#define PARAMETERS_DOORS_DOOR_REP_11_TRACK_NUMBER_ADDR 0x0609
#define PARAMETERS_DOORS_DOOR_REP_11_TRACK_NUMBER_SIZE 1

/* Parameters -> Doors -> Door -> REP_12 -> Description */
#define PARAMETERS_DOORS_DOOR_REP_12_DESCRIPTION_ADDR 0x060A
#define PARAMETERS_DOORS_DOOR_REP_12_DESCRIPTION_SIZE 16

/* Parameters -> Doors -> Door -> REP_12 -> Short Name */
#define PARAMETERS_DOORS_DOOR_REP_12_SHORT_NAME_ADDR 0x061A
#define PARAMETERS_DOORS_DOOR_REP_12_SHORT_NAME_SIZE 5

/* Parameters -> Doors -> Door -> REP_12 -> Toggle Door */
#define PARAMETERS_DOORS_DOOR_REP_12_TOGGLE_DOOR_ADDR 0x061F
#define PARAMETERS_DOORS_DOOR_REP_12_TOGGLE_DOOR_SIZE 8

/* Parameters -> Doors -> Door -> REP_12 -> Track Number */
#define PARAMETERS_DOORS_DOOR_REP_12_TRACK_NUMBER_ADDR 0x0627
#define PARAMETERS_DOORS_DOOR_REP_12_TRACK_NUMBER_SIZE 1

/* Parameters -> Doors -> Door -> REP_13 -> Description */
#define PARAMETERS_DOORS_DOOR_REP_13_DESCRIPTION_ADDR 0x0628
#define PARAMETERS_DOORS_DOOR_REP_13_DESCRIPTION_SIZE 16

/* Parameters -> Doors -> Door -> REP_13 -> Short Name */
#define PARAMETERS_DOORS_DOOR_REP_13_SHORT_NAME_ADDR 0x0638
#define PARAMETERS_DOORS_DOOR_REP_13_SHORT_NAME_SIZE 5

/* Parameters -> Doors -> Door -> REP_13 -> Toggle Door */
#define PARAMETERS_DOORS_DOOR_REP_13_TOGGLE_DOOR_ADDR 0x063D
#define PARAMETERS_DOORS_DOOR_REP_13_TOGGLE_DOOR_SIZE 8

/* Parameters -> Doors -> Door -> REP_13 -> Track Number */
#define PARAMETERS_DOORS_DOOR_REP_13_TRACK_NUMBER_ADDR 0x0645
#define PARAMETERS_DOORS_DOOR_REP_13_TRACK_NUMBER_SIZE 1

/* Parameters -> Doors -> Door -> REP_14 -> Description */
#define PARAMETERS_DOORS_DOOR_REP_14_DESCRIPTION_ADDR 0x0646
#define PARAMETERS_DOORS_DOOR_REP_14_DESCRIPTION_SIZE 16

/* Parameters -> Doors -> Door -> REP_14 -> Short Name */
#define PARAMETERS_DOORS_DOOR_REP_14_SHORT_NAME_ADDR 0x0656
#define PARAMETERS_DOORS_DOOR_REP_14_SHORT_NAME_SIZE 5

/* Parameters -> Doors -> Door -> REP_14 -> Toggle Door */
#define PARAMETERS_DOORS_DOOR_REP_14_TOGGLE_DOOR_ADDR 0x065B
#define PARAMETERS_DOORS_DOOR_REP_14_TOGGLE_DOOR_SIZE 8

/* Parameters -> Doors -> Door -> REP_14 -> Track Number */
#define PARAMETERS_DOORS_DOOR_REP_14_TRACK_NUMBER_ADDR 0x0663
#define PARAMETERS_DOORS_DOOR_REP_14_TRACK_NUMBER_SIZE 1

/* Parameters -> Doors -> Door -> REP_15 -> Description */
#define PARAMETERS_DOORS_DOOR_REP_15_DESCRIPTION_ADDR 0x0664
#define PARAMETERS_DOORS_DOOR_REP_15_DESCRIPTION_SIZE 16

/* Parameters -> Doors -> Door -> REP_15 -> Short Name */
#define PARAMETERS_DOORS_DOOR_REP_15_SHORT_NAME_ADDR 0x0674
#define PARAMETERS_DOORS_DOOR_REP_15_SHORT_NAME_SIZE 5

/* Parameters -> Doors -> Door -> REP_15 -> Toggle Door */
#define PARAMETERS_DOORS_DOOR_REP_15_TOGGLE_DOOR_ADDR 0x0679
#define PARAMETERS_DOORS_DOOR_REP_15_TOGGLE_DOOR_SIZE 8

/* Parameters -> Doors -> Door -> REP_15 -> Track Number */
#define PARAMETERS_DOORS_DOOR_REP_15_TRACK_NUMBER_ADDR 0x0681
#define PARAMETERS_DOORS_DOOR_REP_15_TRACK_NUMBER_SIZE 1

/* Parameters -> Lights -> Toggle Bridge Lights */
#define PARAMETERS_LIGHTS_TOGGLE_BRIDGE_LIGHTS_ADDR 0x0682
#define PARAMETERS_LIGHTS_TOGGLE_BRIDGE_LIGHTS_SIZE 8

/* Parameters -> Lights -> Toggle Interior Lights */
#define PARAMETERS_LIGHTS_TOGGLE_INTERIOR_LIGHTS_ADDR 0x068A
#define PARAMETERS_LIGHTS_TOGGLE_INTERIOR_LIGHTS_SIZE 8

/* Parameters -> Lights -> Toggle Exterior Lights */
#define PARAMETERS_LIGHTS_TOGGLE_EXTERIOR_LIGHTS_ADDR 0x0692
#define PARAMETERS_LIGHTS_TOGGLE_EXTERIOR_LIGHTS_SIZE 8

/* Parameters -> Lights -> Maximum Luminosity */
#define PARAMETERS_LIGHTS_MAXIMUM_LUMINOSITY_ADDR 0x069A
#define PARAMETERS_LIGHTS_MAXIMUM_LUMINOSITY_SIZE 1

/* Parameters -> Lights -> Full Luminosity On */
#define PARAMETERS_LIGHTS_FULL_LUMINOSITY_ON_ADDR 0x069B
#define PARAMETERS_LIGHTS_FULL_LUMINOSITY_ON_SIZE 8

/* Parameters -> Lights -> Minimum Luminosity */
#define PARAMETERS_LIGHTS_MINIMUM_LUMINOSITY_ADDR 0x06A3
#define PARAMETERS_LIGHTS_MINIMUM_LUMINOSITY_SIZE 1

/* Parameters -> Lights -> Low Luminosity On */
#define PARAMETERS_LIGHTS_LOW_LUMINOSITY_ON_ADDR 0x06A4
#define PARAMETERS_LIGHTS_LOW_LUMINOSITY_ON_SIZE 8

#endif // CONFIG_MEM_MAP_H
